# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0002_auto_20170818_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 16, 37, 29, 408443)),
        ),
        migrations.AddField(
            model_name='product',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 16, 37, 29, 406619)),
        ),
    ]
