# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0004_auto_20170820_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 19, 38, 1, 327871)),
        ),
    ]
