# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0005_auto_20170820_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 19, 51, 32, 521783)),
        ),
    ]
