# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0010_auto_20170823_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 20, 7, 2, 436185, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 20, 7, 2, 434380, tzinfo=utc)),
        ),
    ]
