# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0011_auto_20170823_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cookie/media', verbose_name='Фото')),
                ('main', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, upload_to='cookie/media', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 12, 8, 20, 302043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 12, 8, 20, 300315, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='photoproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie.Product'),
        ),
    ]
