# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0012_auto_20170826_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 12, 11, 7, 122767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='photoproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookie.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 12, 11, 7, 121191, tzinfo=utc)),
        ),
    ]
